(block Date_Printer
   (format t "Enter two integers.  Press return after each integer.~%")
   (setq month (read))
   (setq day (read))
   (cond
     ((and (eq month 1) (>= day 1) (<= day 31)) (format t "~a ~a" "January" day))
     ((and (eq month 2) (>= day 1) (<= day 29)) (format t "~a ~a" "February" day))
     ((and (eq month 3) (>= day 1) (<= day 31)) (format t "~a ~a" "March" day))
     ((and (eq month 4) (>= day 1) (<= day 30)) (format t "~a ~a" "April" day))
     ((and (eq month 5) (>= day 1) (<= day 31)) (format t "~a ~a" "May" day))
     ((and (eq month 6) (>= day 1) (<= day 30)) (format t "~a ~a" "June" day))
     ((and (eq month 7) (>= day 1) (<= day 31)) (format t "~a ~a" "July" day))
     ((and (eq month 8) (>= day 1) (<= day 31)) (format t "~a ~a" "August" day))
     ((and (eq month 9) (>= day 1) (<= day 30)) (format t "~a ~a" "September" day))
     ((and (eq month 10) (>= day 1) (<= day 31)) (format t "~a ~a" "October" day))
     ((and (eq month 11) (>= day 1) (<= day 30)) (format t "~a ~a" "November" day))
     ((and (eq month 12) (>= day 1) (<= day 31)) (format t "~a ~a" "December" day))
     (T (format t "~a" "Invalid Date") (return-from Date_Printer)) 
     )
   (cond
     ((member day '(1 21 31)) (format t "~a" "st"))	     
     ((member day '(2 22)) (format t "~a" "nd"))
     ((member day '(3 23)) (format t "~a" "rd"))
     (T (format t "~a" "th"))
     )
   )
