(defun Adder()
	   (terpri)
	   (princ "Enter a number: ")
	   (setq numb1(read))
	   (princ "Enter another number: ")
	   (setq numb2(read))
	   (setq sum(+ numb1 numb2))
	   (write sum))
(Subtractor)
